//Copyright © 2000-2003 by Dmitry A. Sokolyuk
unit UTTaskConsts;

interface

ResourceString
  cstskMTNone='tskMTNone';
  cstskMTDestroyMate='tskMTDestroyMate';
  cstskMTSetPerpetualMate='tskMTSetPerpetualMate'; 
  cstskMTReadEServerPipe='tskMTReadEServerPipe';
  cstskMTSendMessToId='tskMTSendMessToId';
  cstskMTSendMessToUser='tskMTSendMessToUser';
  cstskMTSendMessToAll='tskMTSendMessToAll';
  cstskMTStopAllASM='tskMTStopAllASM';
  cstskMTStopASMOnID='tskMTStopASMOnID';
  cstskMTStopASMOnUser='tskMTStopASMOnUser';
  cstskMTShotDownServer='tskMTShotDownServer';
  cstskMTShotDownServerImmediately='tskMTShotDownServerImmediately';
  cstskMTSendEvent='tskMTSendEvent';
  cstskMTSendEventToOneOfList='tskMTSendEventToOneOfList';
  cstskMTSendEventViaBridge='tskMTSendEventViaBridge';
  cstskMTSendCommand='tskMTSendCommand';
  cstskMTSendCommandViaBridge='tskMTSendCommandViaBridge';
  cstskMTAutoExecuteCommand='tskMTAutoExecuteCommand';
  cstskMTUpdateASMList='tskMTUpdateASMList';
  cstskMTCancelTask='tskMTCancelTask';
  cstskMTIgnoreTaskAdd='tskMTIgnoreTaskAdd';
  cstskMTIgnoreTaskCancel='tskMTIgnoreTaskCancel';
  cstskMTPD='tskMTPD';
  cstskMTPDConnectionName='tskMTPDConnectionName';
  cstskMTMessToLog='tskMTMessToLog';
  cstskMTTableCommand='tskMTTableCommand';
  cstskMTBlockSQLExec='tskMTBlockSQLExec';
  cstskMTCreateBridge='tskMTCreateBridge';
  cstskMTConnectBridge='tskMTConnectBridge';
  cstskMTOnLineCheck='tskMTOnLineCheck';
  cstskMTOnLineSet='tskMTOnLineSet';
  cstskMTOffLineSet='tskMTOffLineSet';
  cstskMTCircleOnLineSetForASM='tskMTCircleOnLineSetForASM';
  cstskMTReloadSecurity='tskMTReloadSecurity';
  //cstskMTInternalConfig='tskMTInternalConfig';
  cstskMTSleepRunner='tskMTSleepRunner';
  cstskMTRunServerProc='tskMTRunServerProc';
  cstskMTCPT='tskMTCPT';
  cstskMTCPR='tskMTCPR';
  cstskMTRePD='tskMTRePD';
  cstskMTExecServerProc='tskMTExecServerProc';
  cstskMTIPD='tskMTIPD';
  cstskMTReloadTriggers='tskMTReloadTriggers';
  cstskMTServerProcedures='tskMTServerProcedures';
  cstskMTSyncTime='tskMTSyncTime';
  cstskMTBfCheckTransfer='tskMTBfCheckTransfer';
  cstskMTBfCheckActuality='tskMTBfCheckActuality';
  cstskMTBfBeginDownload='tskMTBfBeginDownload';
  cstskMTBfDownload='tskMTBfDownload';
  cstskMTBfEndDownload='tskMTBfEndDownload';
  cstskMTBfBeginUpload='tskMTBfBeginUpload';
  cstskMTBfUpload='tskMTBfUpload';
  cstskMTBfEndUpload='tskMTBfEndUpload';
  cstskMTBfReceiveBeginDownload='tskMTBfReceiveBeginDownload';
  cstskMTBfReceiveDownload='tskMTBfReceiveDownload';
  cstskMTBfReceiveEndDownload_UNUSED='tskMTBfReceiveEndDownload_UNUSED';
  cstskMTBfReceiveBeginUpload='tskMTBfReceiveBeginUpload';
  cstskMTBfReceiveUpload='tskMTBfReceiveUpload';
  cstskMTBfReceiveEndUpload='tskMTBfReceiveEndUpload';
  cstskMTBfReceiveErrorBeginDownload='tskMTBfReceiveErrorBeginDownload';
  cstskMTBfReceiveErrorDownload='tskMTBfReceiveErrorDownload';
  cstskMTBfReceiveErrorEndDownload_UNUSED='tskMTBfReceiveErrorEndDownload_UNUSED';
  cstskMTBfReceiveErrorBeginUpload='tskMTBfReceiveErrorBeginUpload';
  cstskMTBfReceiveErrorUpload='tskMTBfReceiveErrorUpload';
  cstskMTBfReceiveErrorEndUpload='tskMTBfReceiveErrorEndUpload';
  cstskMTBfAddTransferDownload='tskMTBfAddTransferDownload';
  cstskMTBfAddTransferUpload='tskMTBfAddTransferUpload';
  cstskMTBfTransferCancel='tskMTBfTransferCancel';
  cstskMTBfTransferCheckProcess='tskMTBfTransferCheckProcess';
  cstskMTBfExists='tskMTBfExists';
  cstskMTBfLocalDelete='tskMTBfLocalDelete';
  cstskMTBfTransferTerminateByBfName='tskMTBfTransferTerminateByBfName';
  cstskMTEQueryInterface='tskMTEQueryInterface';
  cstskMTEQueryInterfaceByLevel='tskMTEQueryInterfaceByLevel';
  cstskMTEQueryInterfaceByNodeName='tskMTEQueryInterfaceByNodeName';

implementation

end.
 