//Copyright © 2000-2003 by Dmitry A. Sokolyuk
unit UADMTypes;

interface

Type
  TADMTask = (
    tskADMNone,                //:TADMTask=0;
    //ADM command
    tskADMGetAbout,            //:TADMTask=1;
    tskADMGetNewMess,          //:TADMTask=2;
    tskADMGetASMServers,       //:TADMTask=3;
    tskADMGetSummJurnal,       //:TADMTask=4;
    tskADMStopASMOnID,         //:TADMTask=5;
    tskADMStopASMOnUser,       //:TADMTask=6;
    tskADMStopASMAll,          //:TADMTask=7;
    tskADMGetServerLockStatus, //:TADMTask=8;
    tskADMServerLock,          //:TADMTask=9;
    tskADMServerUnlock,        //:TADMTask=10;
    tskADMSendMessToId,        //:TADMTask=11;
    tskADMSendMessToUser,      //:TADMTask=12;
    tskADMSendMessToAll,       //:TADMTask=13;
    tskADMCodeOfMateTeam,      //:TADMTask=14;
    tskADMShotDownServer,      //:TADMTask=15;
    tskADMMessage,             //:TADMTask=16;
    tskADMCancelTask,          //:TADMTask=17;
    tskADMIgnoreTaskAdd,       //:TADMTask=18;
    tskADMIgnoreTaskCancel,    //:TADMTask=19;
    tskADMPack,                //:TADMTask=20;
    tskADMSendSaleBlockSQL___DEL,//:TADMTask=21; - Отправка в дальнюю базу блока SQL команд из Dll EMServer-а. Отперация выполняется
                               //                отдельной коммандой т.к. необходимо по прибытии поместить результат в определенную очередь.
    tskADMBlockSQL,            //:TADMTask=22; - Update LocalDataBase на EMServer через мост с сервера Pegas(TableCommand) при помощи
                               //                BlockSQL. Это часть средства поддержания актуальных данных на LDB(tskADMTableCommandBlockSQL).
    tskADMReloadSecurity,      //:TADMTask=23;
    tskADMReloadInternalConfig,//:TADMTask=24;
    tskADMSendMessToMask,      //:TADMTask=25;
    tskADMSendPackToId,        //:TADMTask=26;
    tskADMSendPackToUser,      //:TADMTask=27;
    tskADMSendPackToMask,      //:TADMTask=28;
    tskADMSendPackToAll,       //:TADMTask=29;
    // User command
    tskADMUser_0,              //:TADMTask=30;
    tskADMUser_1,              //:TADMTask=31;
    tskADMUser_2,              //:TADMTask=32;
    tskADMUser_3,              //:TADMTask=33;
    tskADMUser_4,              //:TADMTask=34;
    tskADMUser_5,              //:TADMTask=35;
    tskADMUser_6,              //:TADMTask=36;
    tskADMUser_7,              //:TADMTask=37;
    tskADMUser_8,              //:TADMTask=38;
    tskADMUser_9,              //:TADMTask=39;
    tskADMUser_10,             //:TADMTask=40;
    tskADMUser_11,             //:TADMTask=41;
    tskADMUser_12,             //:TADMTask=42;
    tskADMUser_13,             //:TADMTask=43;
    tskADMUser_14,             //:TADMTask=44;
    tskADMUser_15,             //:TADMTask=45;
    tskADMUser_16,             //:TADMTask=46;
    tskADMUser_17,             //:TADMTask=47;
    tskADMUser_18,             //:TADMTask=48;
    tskADMUser_19,             //:TADMTask=49;
    tskADMUser_20,             //:TADMTask=50;
    tskADMUser_21,             //:TADMTask=51;
    tskADMUser_22,             //:TADMTask=52;
    tskADMUser_23,             //:TADMTask=53;
    tskADMUser_24,             //:TADMTask=54;
    tskADMUser_25,             //:TADMTask=55;
    tskADMUser_26,             //:TADMTask=56;
    tskADMUser_27,             //:TADMTask=57;
    tskADMUser_28,             //:TADMTask=58;
    tskADMUser_29,             //:TADMTask=59;
    tskADMUser_30,             //:TADMTask=60;
    tskADMUser_31,             //:TADMTask=61;
    tskADMUser_32,             //:TADMTask=62;
    tskADMUser_33,             //:TADMTask=63;
    tskADMUser_34,             //:TADMTask=64;
    tskADMUser_35,             //:TADMTask=65;
    tskADMUser_36,             //:TADMTask=66;
    tskADMUser_37,             //:TADMTask=67;
    tskADMUser_38,             //:TADMTask=68;
    tskADMUser_39,             //:TADMTask=69;
    tskADMUser_40,             //:TADMTask=70;
    tskADMUser_41,             //:TADMTask=71;
    tskADMUser_42,             //:TADMTask=72;
    tskADMUser_43,             //:TADMTask=73;
    tskADMUser_44,             //:TADMTask=74;
    tskADMUser_45,             //:TADMTask=75;
    tskADMUser_46,             //:TADMTask=76;
    tskADMUser_47,             //:TADMTask=77;
    tskADMUser_48,             //:TADMTask=78;
    tskADMUser_49,             //:TADMTask=79;
    // ADM command
    tskADMSetLockList,         //:TADMTask=80;
    tskADMGetLockList,         //:TADMTask=81;
    tskADMClearLockOwner,      //:TADMTask=82;
    tskADMRunServerProc,       //:TADMTask=83;
    tskADMCPT,                 //:TADMTask=84;
    tskADMCPR,                 //:TADMTask=85;
    tskADMPD,                  //:TADMTask=86;
    tskADMExecMT,              //:TADMTask=87;
    tskADMGetOnlineStatus,     //:TADMTask=88;
    tskADMGetOnlineMode,       //:TADMTask=89;
    tskADMSetOnlineMode,       //:TADMTask=90;
    tskADMSetOnline,           //:TADMTask=91;
    tskADMSetOffline,          //:TADMTask=92;
    tskADMGetBridgeCount,      //:TADMTask=93;
    tskADMCreateBridge,        //:TADMTask=94;
    tskADMDeleteBridge,        //:TADMTask=95;
    tskADMReserved_16,         //:TADMTask=96;
    tskADMReserved_17,         //:TADMTask=97;
    tskADMReserved_18,         //:TADMTask=98;
    tskADMReserved_19,         //:TADMTask=99;
    // Shop command for EMServar.
    tskADMAddToClientQueue,    //:TADMTask=100;
    tskADMExecServerProc{AddToSendSaleQueue},  //:TADMTask=101;
    tskADMClearRePDOfClientID, //:TADMTask=102;
    tskADMResForSh_3,          //:TADMTask=103;
    tskADMResForSh_4,          //:TADMTask=104;
    tskADMResForSh_5,          //:TADMTask=105;
    tskADMResForSh_6,          //:TADMTask=106;
    tskADMResForSh_7,          //:TADMTask=107;
    tskADMResForSh_8,          //:TADMTask=108;
    tskADMResForSh_9,          //:TADMTask=109;
    tskADMResForSh_10,         //:TADMTask=110;
    tskADMResForSh_11,         //:TADMTask=111;
    tskADMResForSh_12,         //:TADMTask=112;
    tskADMResForSh_13,         //:TADMTask=113;
    tskADMResForSh_14,         //:TADMTask=114;
    tskADMResForSh_15,         //:TADMTask=115;
    tskADMResForSh_16,         //:TADMTask=116;
    tskADMResForSh_17,         //:TADMTask=117;
    tskADMResForSh_18,         //:TADMTask=118;
    tskADMResForSh_19,         //:TADMTask=119;
    tskADMResForSh_20,         //:TADMTask=120;
    tskADMResForSh_21,         //:TADMTask=121;
    tskADMResForSh_22,         //:TADMTask=122;
    tskADMResForSh_23,         //:TADMTask=123;
    tskADMResForSh_24,         //:TADMTask=124;
    tskADMResForSh_25,         //:TADMTask=125;
    tskADMResForSh_26,         //:TADMTask=126;
    tskADMResForSh_27,         //:TADMTask=127;
    tskADMResForSh_28,         //:TADMTask=128;
    tskADMResForSh_29,         //:TADMTask=129;
    tskADMResForSh_30,         //:TADMTask=130;
    tskADMResForSh_31,         //:TADMTask=131;
    tskADMResForSh_32,         //:TADMTask=132;
    tskADMResForSh_33,         //:TADMTask=133;
    tskADMResForSh_34,         //:TADMTask=134;
    tskADMResForSh_35,         //:TADMTask=135;
    tskADMResForSh_36,         //:TADMTask=136;
    tskADMResForSh_37,         //:TADMTask=137;
    tskADMResForSh_38,         //:TADMTask=138;
    tskADMResForSh_39,         //:TADMTask=139;
    tskADMResForSh_40,         //:TADMTask=140;
    tskADMResForSh_41,         //:TADMTask=141;
    tskADMResForSh_42,         //:TADMTask=142;
    tskADMResForSh_43,         //:TADMTask=143;
    tskADMResForSh_44,         //:TADMTask=144;
    tskADMResForSh_45,         //:TADMTask=145;
    tskADMResForSh_46,         //:TADMTask=146;
    tskADMResForSh_47,         //:TADMTask=147;
    tskADMResForSh_48,         //:TADMTask=148;
    tskADMResForSh_49,         //:TADMTask=149;
    tskADMResForSh_50,         //:TADMTask=150;
    //ADM command
    tskADMReserved_151,//tskADMBfCheckActuality,    //:TADMTask=151;
    tskADMReserved_152,//tskADMBfBeginDownload,     //:TADMTask=152;
    tskADMReserved_153,//tskADMBfDownload,          //:TADMTask=153;
    tskADMReserved_154,//tskADMBfEndDownload,       //:TADMTask=154;
    tskADMReserved_155,//tskADMBfBeginUpload,       //:TADMTask=155;
    tskADMReserved_156,//tskADMBfUpload,            //:TADMTask=156;
    tskADMReserved_157,//tskADMBfEndUpload,         //:TADMTask=157;
    tskADMReserved_158,//tskADMBfTransferCancel,    //:TADMTask=158; Отказаться от перекачки. Т.е. отказывается конкретный Caller, а если есть др. Caller-ы то для них перекачка продолжается.
    tskADMReserved_159,//tskADMBfAddTransferDownload,//:TADMTask=159;
    tskADMReserved_160,//tskADMBfAddTransferUpload, //:TADMTask=160;
    tskADMReserved_161,//tskADMBfExists,            //:TADMTask=161;
    tskADMReserved_162,//tskADMBfTransferCanceled,  //:TADMTask=162; Только CPR. Эта команда может быть возвращена только в CPR. Извещает Responder-а об отказе о перекачки.
    tskADMReserved_163,//tskADMBfTransferTerminate, //:TADMTask=163; Прервать перекачку. Перекачка прерывается без условий(проверок) и для всех пользователей этой перекачки.
    tskADMReserved_164,//tskADMBfTransferTerminated,//:TADMTask=164; Только CPR. Извещает Responder-а о прекращении перекачки.
    tskADMReserved_165,//tskADMBfLocalDelete,       //:TADMTask=165;
    tskADMReserved_166,//tskADMBfTransferTerminateByBfName,//:TADMTask=166;
    tskADMEQueryInterface,     //:TADMTask=167;
    tskADMEQueryInterfaceByLevel,//:TADMTask=168;
    tskADMEQueryInterfaceByNodeName,//:TADMTask=169;
    tskADMReserved_170,        //:TADMTask=170;
    tskADMReserved_171,        //:TADMTask=171;
    tskADMReserved_172,        //:TADMTask=172;
    tskADMReserved_173,        //:TADMTask=173;
    tskADMReserved_174,        //:TADMTask=174;
    tskADMReserved_175,        //:TADMTask=175;
    tskADMReserved_176,        //:TADMTask=176;
    tskADMReserved_177,        //:TADMTask=177;
    tskADMReserved_178,        //:TADMTask=178;
    tskADMReserved_179,        //:TADMTask=179;
    tskADMReserved_180,        //:TADMTask=180;
    tskADMReserved_181,        //:TADMTask=181;
    tskADMReserved_182,        //:TADMTask=182;
    tskADMReserved_183,        //:TADMTask=183;
    tskADMReserved_184,        //:TADMTask=184;
    tskADMReserved_185,        //:TADMTask=185;
    tskADMReserved_186,        //:TADMTask=186;
    tskADMReserved_187,        //:TADMTask=187;
    tskADMReserved_188,        //:TADMTask=188;
    tskADMReserved_189,        //:TADMTask=189;
    tskADMReserved_190,        //:TADMTask=190;
    tskADMReserved_191,        //:TADMTask=191;
    tskADMReserved_192,        //:TADMTask=192;
    tskADMReserved_193,        //:TADMTask=193;
    tskADMReserved_194,        //:TADMTask=194;
    tskADMReserved_195,        //:TADMTask=195;
    tskADMReserved_196,        //:TADMTask=196;
    tskADMReserved_197,        //:TADMTask=197;
    tskADMReserved_198,        //:TADMTask=198;
    tskADMReserved_199,        //:TADMTask=199;
    tskADMPackIsLost           //:TADMTask=200; Только CPR. Эта команда может быть возвращена только в CPR.
    );


implementation

end.
